import { Skill, SubSkill } from "@prisma/client";

export const SKILL_VALUES = Object.values(Skill);
export const SUB_SKILL_VALUES = Object.values(SubSkill);

export type SkillValue = (typeof SKILL_VALUES)[number];
export type SubSkillValue = (typeof SUB_SKILL_VALUES)[number];

export const uniqueSkillValues = <T extends SkillValue | SubSkillValue>(
  values: T[] | undefined,
): T[] | undefined => {
  if (!values) {
    return undefined;
  }

  return [...new Set(values)];
};

export const SUB_SKILLS_BY_SKILL: Record<SkillValue, SubSkillValue[]> = {
  [Skill.FRONTEND_DEVELOPMENT]: [
    SubSkill.HTML,
    SubSkill.CSS,
    SubSkill.JAVASCRIPT,
    SubSkill.TYPESCRIPT,
    SubSkill.REACT,
    SubSkill.NEXTJS,
    SubSkill.VUE,
    SubSkill.NUXTJS,
    SubSkill.ANGULAR,
    SubSkill.SVELTE,
    SubSkill.ASTRO,
    SubSkill.REMIX,
    SubSkill.TAILWIND_CSS,
    SubSkill.BOOTSTRAP,
    SubSkill.MATERIAL_UI,
    SubSkill.CHAKRA_UI,
    SubSkill.SASS,
    SubSkill.LESS,
    SubSkill.CSS_MODULES,
    SubSkill.STYLED_COMPONENTS,
    SubSkill.FRAMER_MOTION,
    SubSkill.GSAP,
    SubSkill.THREEJS,
    SubSkill.D3JS,
    SubSkill.WEBGL,
    SubSkill.WEBPACK,
    SubSkill.VITE,
    SubSkill.ROLLUP,
    SubSkill.STORYBOOK,
    SubSkill.ACCESSIBILITY,
    SubSkill.RESPONSIVE_DESIGN,
    SubSkill.WEB_PERFORMANCE,
    SubSkill.PWA,
    SubSkill.SEO,
    SubSkill.BROWSER_EXTENSIONS,
  ],
  [Skill.BACKEND_DEVELOPMENT]: [
    SubSkill.NODEJS,
    SubSkill.EXPRESSJS,
    SubSkill.NESTJS,
    SubSkill.FASTIFY,
    SubSkill.BUN,
    SubSkill.DENO,
    SubSkill.PYTHON,
    SubSkill.DJANGO,
    SubSkill.FLASK,
    SubSkill.FASTAPI,
    SubSkill.PHP,
    SubSkill.LARAVEL,
    SubSkill.SYMFONY,
    SubSkill.RUBY,
    SubSkill.RUBY_ON_RAILS,
    SubSkill.JAVA,
    SubSkill.SPRING_BOOT,
    SubSkill.KOTLIN,
    SubSkill.SCALA,
    SubSkill.GO,
    SubSkill.GIN,
    SubSkill.RUST,
    SubSkill.ACTIX,
    SubSkill.C_SHARP,
    SubSkill.DOTNET,
    SubSkill.ELIXIR,
    SubSkill.PHOENIX,
    SubSkill.GRAPHQL,
    SubSkill.REST_API,
    SubSkill.GRPC,
    SubSkill.WEBSOCKET,
    SubSkill.MICROSERVICES,
    SubSkill.EVENT_DRIVEN_ARCHITECTURE,
    SubSkill.SERVERLESS,
    SubSkill.API_DESIGN,
    SubSkill.OAUTH,
    SubSkill.SSO,
    SubSkill.JWT,
    SubSkill.RBAC,
    SubSkill.ABAC,
  ],
  [Skill.FULLSTACK_DEVELOPMENT]: [
    SubSkill.TYPESCRIPT,
    SubSkill.REACT,
    SubSkill.NEXTJS,
    SubSkill.NODEJS,
    SubSkill.EXPRESSJS,
    SubSkill.NESTJS,
    SubSkill.GRAPHQL,
    SubSkill.REST_API,
    SubSkill.POSTGRESQL,
    SubSkill.MONGODB,
    SubSkill.REDIS,
    SubSkill.PRISMA,
    SubSkill.DOCKER,
    SubSkill.SUPABASE,
    SubSkill.FIREBASE,
  ],
  [Skill.MOBILE_DEVELOPMENT]: [
    SubSkill.REACT_NATIVE,
    SubSkill.FLUTTER,
    SubSkill.ANDROID_NATIVE,
    SubSkill.IOS_NATIVE,
    SubSkill.SWIFT,
    SubSkill.SWIFTUI,
    SubSkill.OBJECTIVE_C,
    SubSkill.KOTLIN_ANDROID,
    SubSkill.JETPACK_COMPOSE,
    SubSkill.DART,
    SubSkill.EXPO,
    SubSkill.MOBILE_UI,
    SubSkill.MOBILE_PERFORMANCE,
    SubSkill.APP_STORE_RELEASE,
    SubSkill.PUSH_NOTIFICATIONS,
  ],
  [Skill.DESKTOP_DEVELOPMENT]: [
    SubSkill.ELECTRON,
    SubSkill.TAURI,
    SubSkill.QT,
    SubSkill.WPF,
    SubSkill.WINUI,
    SubSkill.C_SHARP,
    SubSkill.DOTNET,
    SubSkill.RUST,
  ],
  [Skill.GAME_DEVELOPMENT]: [
    SubSkill.UNITY,
    SubSkill.UNREAL_ENGINE,
    SubSkill.GODOT,
    SubSkill.COCOS_CREATOR,
    SubSkill.GAME_DESIGN,
    SubSkill.LEVEL_DESIGN,
    SubSkill.GAME_PHYSICS,
    SubSkill.BLENDER,
  ],
  [Skill.UI_UX_DESIGN]: [
    SubSkill.FIGMA,
    SubSkill.DESIGN_SYSTEMS,
    SubSkill.WIREFRAMING,
    SubSkill.PROTOTYPING,
    SubSkill.USER_RESEARCH,
    SubSkill.USABILITY_TESTING,
    SubSkill.INFORMATION_ARCHITECTURE,
    SubSkill.INTERACTION_DESIGN,
    SubSkill.VISUAL_DESIGN,
    SubSkill.ACCESSIBILITY,
  ],
  [Skill.GRAPHIC_DESIGN]: [
    SubSkill.FIGMA,
    SubSkill.VISUAL_DESIGN,
    SubSkill.BLENDER,
    SubSkill.MAYA,
    SubSkill.CINEMA_4D,
    SubSkill.THREE_D_MODELING,
    SubSkill.AFTER_EFFECTS,
    SubSkill.MOTION_GRAPHICS,
  ],
  [Skill.BRAND_DESIGN]: [
    SubSkill.FIGMA,
    SubSkill.DESIGN_SYSTEMS,
    SubSkill.VISUAL_DESIGN,
    SubSkill.COPYWRITING,
    SubSkill.SOCIAL_MEDIA_MARKETING,
  ],
  [Skill.PRODUCT_MANAGEMENT]: [
    SubSkill.PRODUCT_STRATEGY,
    SubSkill.ROADMAPPING,
    SubSkill.PRD,
    SubSkill.USER_STORIES,
    SubSkill.AGILE,
    SubSkill.SCRUM,
    SubSkill.KANBAN,
    SubSkill.ANALYTICS_INSTRUMENTATION,
    SubSkill.A_B_TESTING,
    SubSkill.MARKET_RESEARCH,
  ],
  [Skill.PROJECT_MANAGEMENT]: [
    SubSkill.AGILE,
    SubSkill.SCRUM,
    SubSkill.KANBAN,
    SubSkill.USER_STORIES,
    SubSkill.BUSINESS_ANALYSIS,
    SubSkill.DOCUMENTATION,
  ],
  [Skill.QUALITY_ASSURANCE]: [
    SubSkill.UNIT_TESTING,
    SubSkill.INTEGRATION_TESTING,
    SubSkill.E2E_TESTING,
    SubSkill.PLAYWRIGHT,
    SubSkill.CYPRESS,
    SubSkill.SELENIUM,
    SubSkill.VITEST,
    SubSkill.JEST,
    SubSkill.MOCHA,
    SubSkill.POSTMAN,
    SubSkill.LOAD_TESTING,
    SubSkill.K6,
    SubSkill.JMETER,
    SubSkill.TEST_AUTOMATION,
    SubSkill.MANUAL_TESTING,
    SubSkill.QA_STRATEGY,
  ],
  [Skill.DEVOPS_PLATFORM_ENGINEERING]: [
    SubSkill.DOCKER,
    SubSkill.KUBERNETES,
    SubSkill.HELM,
    SubSkill.TERRAFORM,
    SubSkill.PULUMI,
    SubSkill.ANSIBLE,
    SubSkill.NGINX,
    SubSkill.APACHE,
    SubSkill.LINUX,
    SubSkill.BASH,
    SubSkill.CI_CD,
    SubSkill.GITHUB_ACTIONS,
    SubSkill.GITLAB_CI,
    SubSkill.JENKINS,
    SubSkill.ARGOCD,
    SubSkill.PROMETHEUS,
    SubSkill.GRAFANA,
    SubSkill.DATADOG,
    SubSkill.NEW_RELIC,
    SubSkill.OBSERVABILITY,
    SubSkill.SRE,
    SubSkill.INCIDENT_RESPONSE,
  ],
  [Skill.CLOUD_ENGINEERING]: [
    SubSkill.AWS,
    SubSkill.AZURE,
    SubSkill.GOOGLE_CLOUD,
    SubSkill.DIGITALOCEAN,
    SubSkill.CLOUDFLARE,
    SubSkill.SERVERLESS,
    SubSkill.TERRAFORM,
    SubSkill.KUBERNETES,
    SubSkill.CLOUD_SECURITY,
    SubSkill.OBSERVABILITY,
  ],
  [Skill.DATABASE_ENGINEERING]: [
    SubSkill.POSTGRESQL,
    SubSkill.MYSQL,
    SubSkill.MARIADB,
    SubSkill.SQLITE,
    SubSkill.SQL_SERVER,
    SubSkill.ORACLE_DATABASE,
    SubSkill.MONGODB,
    SubSkill.REDIS,
    SubSkill.ELASTICSEARCH,
    SubSkill.OPENSEARCH,
    SubSkill.CASSANDRA,
    SubSkill.DYNAMODB,
    SubSkill.FIREBASE,
    SubSkill.SUPABASE,
    SubSkill.SQL,
    SubSkill.DATABASE_DESIGN,
    SubSkill.QUERY_OPTIMIZATION,
    SubSkill.DATA_MODELING,
    SubSkill.DATABASE_MIGRATION,
  ],
  [Skill.DATA_ENGINEERING]: [
    SubSkill.AIRFLOW,
    SubSkill.DBT,
    SubSkill.SPARK,
    SubSkill.HADOOP,
    SubSkill.KAFKA,
    SubSkill.REDPANDA,
    SubSkill.SNOWFLAKE,
    SubSkill.BIGQUERY,
    SubSkill.REDSHIFT,
    SubSkill.ETL,
    SubSkill.ELT,
    SubSkill.DATA_WAREHOUSE,
    SubSkill.DATA_LAKE,
  ],
  [Skill.DATA_ANALYTICS]: [
    SubSkill.POWER_BI,
    SubSkill.TABLEAU,
    SubSkill.LOOKER,
    SubSkill.EXCEL,
    SubSkill.GOOGLE_SHEETS,
    SubSkill.SQL,
    SubSkill.STATISTICS,
    SubSkill.DATA_VISUALIZATION,
    SubSkill.ANALYTICS_INSTRUMENTATION,
  ],
  [Skill.DATA_SCIENCE]: [
    SubSkill.PYTHON,
    SubSkill.R,
    SubSkill.PANDAS,
    SubSkill.NUMPY,
    SubSkill.JUPYTER,
    SubSkill.STATISTICS,
    SubSkill.DATA_VISUALIZATION,
    SubSkill.SCIKIT_LEARN,
  ],
  [Skill.MACHINE_LEARNING]: [
    SubSkill.SCIKIT_LEARN,
    SubSkill.TENSORFLOW,
    SubSkill.PYTORCH,
    SubSkill.KERAS,
    SubSkill.MLOPS,
    SubSkill.MODEL_DEPLOYMENT,
    SubSkill.COMPUTER_VISION,
    SubSkill.NLP,
  ],
  [Skill.ARTIFICIAL_INTELLIGENCE]: [
    SubSkill.LLM,
    SubSkill.RAG,
    SubSkill.PROMPT_ENGINEERING,
    SubSkill.VECTOR_DATABASES,
    SubSkill.LANGCHAIN,
    SubSkill.LLAMAINDEX,
    SubSkill.OPENAI_API,
    SubSkill.ANTHROPIC_API,
    SubSkill.HUGGING_FACE,
    SubSkill.FINE_TUNING,
    SubSkill.AGENTS,
    SubSkill.OCR,
    SubSkill.SPEECH_TO_TEXT,
  ],
  [Skill.CYBERSECURITY]: [
    SubSkill.APPLICATION_SECURITY,
    SubSkill.NETWORK_SECURITY,
    SubSkill.CLOUD_SECURITY,
    SubSkill.SECURITY_AUDIT,
    SubSkill.PENETRATION_TESTING,
    SubSkill.THREAT_MODELING,
    SubSkill.SIEM,
    SubSkill.SOC,
    SubSkill.IAM,
    SubSkill.ZERO_TRUST,
    SubSkill.OWASP_TOP_10,
    SubSkill.SAST,
    SubSkill.DAST,
    SubSkill.SECRET_MANAGEMENT,
    SubSkill.CRYPTOGRAPHY,
    SubSkill.FORENSICS,
  ],
  [Skill.BLOCKCHAIN_WEB3]: [
    SubSkill.ETHEREUM,
    SubSkill.EVM,
    SubSkill.CELO,
    SubSkill.POLYGON,
    SubSkill.ARBITRUM,
    SubSkill.OPTIMISM,
    SubSkill.BASE,
    SubSkill.SOLANA,
    SubSkill.WEB3JS,
    SubSkill.ETHERSJS,
    SubSkill.VIEM,
    SubSkill.WAGMI,
    SubSkill.THIRDWEB,
    SubSkill.THE_GRAPH,
    SubSkill.IPFS,
    SubSkill.NFTS,
    SubSkill.DEFI,
    SubSkill.DAO,
    SubSkill.TOKENOMICS,
    SubSkill.WALLET_INTEGRATION,
  ],
  [Skill.SMART_CONTRACT_DEVELOPMENT]: [
    SubSkill.SOLIDITY,
    SubSkill.VYPER,
    SubSkill.HARDHAT,
    SubSkill.FOUNDRY,
    SubSkill.ANCHOR,
    SubSkill.RUST_SOLANA,
    SubSkill.SMART_CONTRACT_AUDIT,
    SubSkill.ZK_PROOFS,
  ],
  [Skill.SYSTEM_ARCHITECTURE]: [
    SubSkill.MICROSERVICES,
    SubSkill.EVENT_DRIVEN_ARCHITECTURE,
    SubSkill.API_DESIGN,
    SubSkill.DATABASE_DESIGN,
    SubSkill.CLOUD_SECURITY,
    SubSkill.OBSERVABILITY,
    SubSkill.SRE,
  ],
  [Skill.EMBEDDED_IOT]: [
    SubSkill.RUST,
    SubSkill.PYTHON,
    SubSkill.LINUX,
    SubSkill.BASH,
    SubSkill.AWS,
    SubSkill.GOOGLE_CLOUD,
    SubSkill.NETWORK_SECURITY,
  ],
  [Skill.ROBOTICS]: [
    SubSkill.PYTHON,
    SubSkill.RUST,
    SubSkill.COMPUTER_VISION,
    SubSkill.TENSORFLOW,
    SubSkill.PYTORCH,
    SubSkill.LINUX,
  ],
  [Skill.AR_VR_XR]: [
    SubSkill.UNITY,
    SubSkill.UNREAL_ENGINE,
    SubSkill.THREEJS,
    SubSkill.WEBGL,
    SubSkill.ARKIT,
    SubSkill.ARCORE,
    SubSkill.WEBXR,
  ],
  [Skill.GIS_GEOSPATIAL]: [
    SubSkill.PYTHON,
    SubSkill.POSTGRESQL,
    SubSkill.DATA_VISUALIZATION,
    SubSkill.DATA_MODELING,
  ],
  [Skill.ERP_CRM]: [
    SubSkill.ODOO,
    SubSkill.SAP,
    SubSkill.SALESFORCE,
    SubSkill.HUBSPOT,
    SubSkill.CRM,
    SubSkill.BUSINESS_ANALYSIS,
  ],
  [Skill.NO_CODE_AUTOMATION]: [
    SubSkill.ZAPIER,
    SubSkill.MAKE,
    SubSkill.AIRTABLE,
    SubSkill.NOTION,
    SubSkill.RETOOL,
    SubSkill.BUBBLE,
    SubSkill.WEBFLOW,
    SubSkill.WORDPRESS,
    SubSkill.SHOPIFY,
  ],
  [Skill.TECHNICAL_WRITING]: [
    SubSkill.TECHNICAL_WRITING,
    SubSkill.DOCUMENTATION,
    SubSkill.BLOG_WRITING,
  ],
  [Skill.CONTENT_CREATION]: [
    SubSkill.COPYWRITING,
    SubSkill.BLOG_WRITING,
    SubSkill.SOCIAL_MEDIA_MARKETING,
    SubSkill.SEO_CONTENT,
    SubSkill.EMAIL_MARKETING,
  ],
  [Skill.VIDEO_AUDIO_PRODUCTION]: [
    SubSkill.REMOTION,
    SubSkill.AFTER_EFFECTS,
    SubSkill.PREMIERE_PRO,
    SubSkill.DAVINCI_RESOLVE,
    SubSkill.AUDITION,
    SubSkill.MOTION_GRAPHICS,
  ],
  [Skill.MARKETING_GROWTH]: [
    SubSkill.SOCIAL_MEDIA_MARKETING,
    SubSkill.SEO_CONTENT,
    SubSkill.SEM,
    SubSkill.GOOGLE_ADS,
    SubSkill.META_ADS,
    SubSkill.EMAIL_MARKETING,
    SubSkill.A_B_TESTING,
    SubSkill.ANALYTICS_INSTRUMENTATION,
    SubSkill.MARKET_RESEARCH,
  ],
  [Skill.SALES_BUSINESS_DEVELOPMENT]: [
    SubSkill.CRM,
    SubSkill.SALESFORCE,
    SubSkill.HUBSPOT,
    SubSkill.BUSINESS_ANALYSIS,
    SubSkill.MARKET_RESEARCH,
  ],
  [Skill.CUSTOMER_SUCCESS]: [
    SubSkill.CUSTOMER_SUPPORT,
    SubSkill.CRM,
    SubSkill.HUBSPOT,
    SubSkill.DOCUMENTATION,
    SubSkill.COMMUNITY_BUILDING,
  ],
  [Skill.COMMUNITY_MANAGEMENT]: [
    SubSkill.COMMUNITY_BUILDING,
    SubSkill.SOCIAL_MEDIA_MARKETING,
    SubSkill.EMAIL_MARKETING,
    SubSkill.COPYWRITING,
  ],
  [Skill.OPERATIONS]: [
    SubSkill.BUSINESS_ANALYSIS,
    SubSkill.EXCEL,
    SubSkill.GOOGLE_SHEETS,
    SubSkill.ODOO,
    SubSkill.SAP,
    SubSkill.COMPLIANCE,
  ],
  [Skill.FINANCE_ACCOUNTING]: [
    SubSkill.FINANCIAL_MODELING,
    SubSkill.ACCOUNTING,
    SubSkill.TAX,
    SubSkill.EXCEL,
    SubSkill.GOOGLE_SHEETS,
  ],
  [Skill.LEGAL_COMPLIANCE]: [
    SubSkill.CONTRACT_REVIEW,
    SubSkill.DATA_PRIVACY,
    SubSkill.COMPLIANCE,
    SubSkill.DOCUMENTATION,
  ],
  [Skill.HUMAN_RESOURCES]: [
    SubSkill.RECRUITING,
    SubSkill.PERFORMANCE_MANAGEMENT,
    SubSkill.TRAINING_FACILITATION,
    SubSkill.DOCUMENTATION,
  ],
  [Skill.EDUCATION_TRAINING]: [
    SubSkill.TRAINING_FACILITATION,
    SubSkill.CURRICULUM_DESIGN,
    SubSkill.TECHNICAL_WRITING,
    SubSkill.DOCUMENTATION,
  ],
  [Skill.RESEARCH]: [
    SubSkill.MARKET_RESEARCH,
    SubSkill.USER_RESEARCH,
    SubSkill.STATISTICS,
    SubSkill.DATA_VISUALIZATION,
    SubSkill.DOCUMENTATION,
  ],
  [Skill.QUANT_FINANCE]: [
    SubSkill.PYTHON,
    SubSkill.R,
    SubSkill.PANDAS,
    SubSkill.NUMPY,
    SubSkill.STATISTICS,
    SubSkill.FINANCIAL_MODELING,
  ],
  [Skill.LOCALIZATION_TRANSLATION]: [
    SubSkill.TRANSLATION,
    SubSkill.LOCALIZATION,
    SubSkill.DOCUMENTATION,
  ],
};

export const skillOptions = {
  skills: SKILL_VALUES,
  subSkills: SUB_SKILL_VALUES,
  subSkillsBySkill: SUB_SKILLS_BY_SKILL,
};
